import Head from "next/head";
import Footer from "components/Footer";
import { signOut } from "@lib/auth";

export default function Home() {
	return (
		<>
			<Head>
				<title>V-Form</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/alt-curly-svgrepo-com.ico" />
			</Head>
			<main>
				<h1>Welcome</h1>
				<button onClick={() => signOut()}>SIGN OUT</button>
			</main>
			<Footer />
		</>
	);
}
