name: CI/CD Deploy

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        environment: Production

        steps:
            - uses: actions/checkout@v1
            - name: Build

              run: |
                  npm install
                  npm install -g firebase-tools
                  npm run build
                  touch key.json
                  echo "${{ secrets.FIREBASE_ADMIN }}" > /key.json
                  export GOOGLE_APPLICATION_CREDENTIALS="/key.json"
                  cat /key.json
    
            - name: Firebase Deploy
            env:
                  NEXT_PUBLIC_FIRE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIRE_API_KEY }}
                  NEXT_PUBLIC_FIRE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIRE_APP_ID }}
                  NEXT_PUBLIC_FIRE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIRE_AUTH_DOMAIN }}
                  NEXT_PUBLIC_FIRE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIRE_PROJECT_ID }}
                  NEXT_PUBLIC_FIRE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIRE_STORAGE_BUCKET }}
                  NEXT_PUBLIC_FIRE_MESSAGING: ${{ secrets.NEXT_PUBLIC_FIRE_MESSAGING }}
              run: |
                  firebase experiments:enable webframeworks
                  firebase use v-form-cb250
                  firebase deploy
