name: CI/CD Deploy

on:
    push:
        branches:
            - main

jobs:
    build:
        if: "!contains(github.event.head_commit.message, '[skip-ci]')"
        runs-on: ubuntu-latest
        environment: Production

        steps:
            - name: Checkout branch
              uses: actions/checkout@v1

            - name: Retrieve npm cache (if any)
              uses: actions/cache@v1
              with:
                  path: ~/.npm
                  key: npm-packages

            - name: Build
              run: |
                  npm install
                  npm install -g firebase-tools
                  npm run build

            - name: create-json
              id: create-json
              uses: jsdaniell/create-json@v1.2.2
              with:
                  name: "gcloud.json"
                  json: ${{ secrets.FIREBASE_ADMIN }}
                  dir: "src/"
            - run: git config --global user.email "michaelhmehall@gmail.com" && git config --global user.name "Mike968" && git add . && git add --force src/gcloud.json && git status && git commit -a -m "Deploy Heroku Commit with the Credentials JSON created!"

            - name: Firebase Deploy
              env:
                  NEXT_PUBLIC_FIRE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIRE_API_KEY }}
                  NEXT_PUBLIC_FIRE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIRE_APP_ID }}
                  NEXT_PUBLIC_FIRE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIRE_AUTH_DOMAIN }}
                  NEXT_PUBLIC_FIRE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIRE_PROJECT_ID }}
                  NEXT_PUBLIC_FIRE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIRE_STORAGE_BUCKET }}
                  NEXT_PUBLIC_FIRE_MESSAGING: ${{ secrets.NEXT_PUBLIC_FIRE_MESSAGING }}
                  GOOGLE_APPLICATION_CREDENTIALS: "gcloud.json"
              run: |
                  firebase experiments:enable webframeworks
                  firebase use v-form-cb250
                  firebase deploy
